import { useState } from "react";
import { base44 } from "@/api/base44Client";
import { X, Plus, Trash2, ChevronRight, ChevronDown, CheckCircle2, Mail, Loader2, Pencil } from "lucide-react";

const ROOMS = [
  { id: "living", label: "Living Room", emoji: "🛋️" },
  { id: "kitchen", label: "Kitchen", emoji: "🍳" },
  { id: "master", label: "Master Bedroom", emoji: "🛏️" },
  { id: "bedroom2", label: "Bedroom 2", emoji: "🛏️" },
  { id: "bedroom3", label: "Bedroom 3", emoji: "🚪" },
  { id: "bathroom", label: "Bathroom(s)", emoji: "🚿" },
  { id: "garage", label: "Garage", emoji: "🚗" },
  { id: "office", label: "Office / Den", emoji: "💼" },
  { id: "outdoor", label: "Outdoor / Patio", emoji: "🌿" },
  { id: "storage", label: "Storage / Basement", emoji: "📦" },
];

const DEFAULT_SUGGESTIONS = {
  living: ["Sofa", "Coffee Table", "TV Stand", "Bookcase", "Armchair", "Lamps", "Rugs"],
  kitchen: ["Refrigerator", "Microwave", "Toaster", "Dishes/Glassware", "Pots & Pans", "Small Appliances"],
  master: ["King/Queen Bed Frame", "Mattress", "Dresser", "Nightstands", "Wardrobe", "Mirror"],
  bedroom2: ["Bed Frame", "Mattress", "Dresser", "Desk", "Chair"],
  bedroom3: ["Bed Frame", "Mattress", "Storage Furniture"],
  bathroom: ["Medicine Cabinet", "Towel Racks", "Shower Curtain", "Vanity"],
  garage: ["Workbench", "Shelving Units", "Lawn Equipment", "Tools", "Bikes", "Storage Bins"],
  office: ["Desk", "Office Chair", "Bookcase", "Filing Cabinet", "Computer Setup"],
  outdoor: ["Patio Furniture", "Grill", "Planters", "Outdoor Lighting"],
  storage: ["Storage Shelves", "Seasonal Items", "Holiday Decor", "Sports Equipment"],
};

export default function InventoryWalkthrough({ user, onClose, selectedRooms }) {
  const activeRooms = selectedRooms && selectedRooms.length > 0
    ? ROOMS.filter(r => selectedRooms.includes(r.id))
    : ROOMS;

  const [rooms, setRooms] = useState(() =>
    ROOMS.reduce((acc, r) => ({ ...acc, [r.id]: [] }), {})
  );
  const [expandedRoom, setExpandedRoom] = useState(activeRooms[0]?.id || "living");
  const [newItem, setNewItem] = useState("");
  const [editingItem, setEditingItem] = useState(null); // {roomId, idx}
  const [editText, setEditText] = useState("");
  const [showSummary, setShowSummary] = useState(false);
  const [sending, setSending] = useState(false);
  const [sent, setSent] = useState(false);

  const addItem = (roomId, text) => {
    const val = text.trim();
    if (!val) return;
    setRooms(r => ({ ...r, [roomId]: [...r[roomId], { name: val, bringing: true }] }));
    setNewItem("");
  };

  const toggleBringing = (roomId, idx) => {
    setRooms(r => {
      const updated = [...r[roomId]];
      updated[idx] = { ...updated[idx], bringing: !updated[idx].bringing };
      return { ...r, [roomId]: updated };
    });
  };

  const removeItem = (roomId, idx) => {
    setRooms(r => {
      const updated = [...r[roomId]];
      updated.splice(idx, 1);
      return { ...r, [roomId]: updated };
    });
  };

  const startEdit = (roomId, idx) => {
    setEditingItem({ roomId, idx });
    setEditText(rooms[roomId][idx].name);
  };

  const saveEdit = () => {
    if (!editingItem) return;
    const { roomId, idx } = editingItem;
    setRooms(r => {
      const updated = [...r[roomId]];
      updated[idx] = { ...updated[idx], name: editText.trim() || updated[idx].name };
      return { ...r, [roomId]: updated };
    });
    setEditingItem(null);
    setEditText("");
  };

  const totalBringing = Object.values(rooms).flat().filter(i => i.bringing).length;
  const totalItems = Object.values(rooms).flat().length;

  const buildSummary = () => {
    const lines = [];
    ROOMS.forEach(r => {
      const items = rooms[r.id].filter(i => i.bringing);
      if (items.length) {
        lines.push(`\n${r.emoji} ${r.label}:`);
        items.forEach(i => lines.push(`  • ${i.name}`));
      }
    });
    return lines.join("\n");
  };

  const handleEmail = async () => {
    setSending(true);
    const summary = buildSummary();
    const body = `Hi ${user?.full_name || "there"},\n\nHere's your moving inventory — items you're bringing to your new home:\n${summary}\n\nTotal items: ${totalBringing}\n\nGenerated by EZ Move AI`;
    await base44.integrations.Core.SendEmail({
      to: user?.email,
      subject: "My Moving Inventory — Items to Bring",
      body,
    });
    setSending(false);
    setSent(true);
  };

  const roomsWithItems = ROOMS.filter(r => rooms[r.id].length > 0);

  return (
    <div className="fixed inset-0 bg-black/60 z-50 flex items-end justify-center">
      <div className="bg-white w-full max-w-md rounded-t-3xl max-h-[92vh] flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between px-4 py-4 border-b border-[#F3F4F6]">
          <div>
            <h2 className="text-base font-bold text-[#1A1A2E]">Room-by-Room Inventory</h2>
            <p className="text-[11px] text-[#6B7280]">Mark what you're bringing to your new home</p>
          </div>
          <button onClick={onClose} className="p-1"><X className="w-5 h-5 text-[#6B7280]" /></button>
        </div>

        {!showSummary ? (
          <>
            {/* Room list */}
            <div className="flex-1 overflow-y-auto px-4 py-3 space-y-2">
              {activeRooms.map(room => {
                const isOpen = expandedRoom === room.id;
                const items = rooms[room.id];
                return (
                  <div key={room.id} className="rounded-xl border border-[#F3F4F6] overflow-hidden">
                    <button
                      onClick={() => setExpandedRoom(isOpen ? null : room.id)}
                      className="w-full flex items-center justify-between px-3 py-2.5 bg-[#FAFAFA]"
                    >
                      <div className="flex items-center gap-2">
                        <span>{room.emoji}</span>
                        <span className="text-sm font-semibold text-[#1A1A2E]">{room.label}</span>
                        {items.length > 0 && (
                          <span className="text-[10px] bg-[#FFF7ED] text-[#F97316] font-bold px-1.5 py-0.5 rounded-full">
                            {items.filter(i => i.bringing).length} bringing
                          </span>
                        )}
                      </div>
                      {isOpen ? <ChevronDown className="w-4 h-4 text-[#9CA3AF]" /> : <ChevronRight className="w-4 h-4 text-[#9CA3AF]" />}
                    </button>

                    {isOpen && (
                      <div className="px-3 pb-3 pt-2 space-y-1.5">
                        {/* Existing items */}
                        {items.map((item, idx) => (
                          <div key={idx} className={`flex items-center gap-2 rounded-lg px-2 py-1.5 transition-all ${item.bringing ? "bg-[#FFF7ED]" : "bg-[#F9FAFB] opacity-60"}`}>
                            <button
                              onClick={() => toggleBringing(room.id, idx)}
                              className={`w-5 h-5 rounded-full border-2 flex-shrink-0 flex items-center justify-center transition-all
                                ${item.bringing ? "bg-[#F97316] border-[#F97316]" : "border-[#D1D5DB]"}`}
                            >
                              {item.bringing && <svg className="w-2.5 h-2.5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={3}><path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" /></svg>}
                            </button>
                            {editingItem?.roomId === room.id && editingItem?.idx === idx ? (
                              <input
                                autoFocus
                                value={editText}
                                onChange={e => setEditText(e.target.value)}
                                onBlur={saveEdit}
                                onKeyDown={e => e.key === "Enter" && saveEdit()}
                                className="flex-1 text-xs border border-[#F97316] rounded px-1 py-0.5 outline-none"
                              />
                            ) : (
                              <span className={`flex-1 text-xs font-medium ${item.bringing ? "text-[#1A1A2E]" : "text-[#9CA3AF] line-through"}`}>
                                {item.name}
                              </span>
                            )}
                            <button onClick={() => startEdit(room.id, idx)} className="p-0.5"><Pencil className="w-3 h-3 text-[#9CA3AF]" /></button>
                            <button onClick={() => removeItem(room.id, idx)} className="p-0.5"><Trash2 className="w-3 h-3 text-[#EF4444]" /></button>
                          </div>
                        ))}

                        {/* Quick suggestions */}
                        {DEFAULT_SUGGESTIONS[room.id]?.filter(s => !items.some(i => i.name.toLowerCase() === s.toLowerCase())).length > 0 && (
                          <div className="flex flex-wrap gap-1 mt-1.5">
                            {DEFAULT_SUGGESTIONS[room.id].filter(s => !items.some(i => i.name.toLowerCase() === s.toLowerCase())).slice(0, 5).map(s => (
                              <button
                                key={s}
                                onClick={() => addItem(room.id, s)}
                                className="text-[10px] px-2 py-0.5 rounded-full bg-[#F3F4F6] text-[#6B7280] hover:bg-[#FFF7ED] hover:text-[#F97316] transition-all"
                              >
                                + {s}
                              </button>
                            ))}
                          </div>
                        )}

                        {/* Add custom item */}
                        <div className="flex gap-2 mt-2">
                          <input
                            placeholder="Add custom item…"
                            value={newItem}
                            onChange={e => setNewItem(e.target.value)}
                            onKeyDown={e => e.key === "Enter" && addItem(room.id, newItem)}
                            className="flex-1 px-3 py-1.5 rounded-xl border border-[#E5E7EB] text-xs focus:outline-none focus:border-[#F97316]"
                          />
                          <button
                            onClick={() => addItem(room.id, newItem)}
                            className="p-1.5 bg-[#F97316] rounded-xl"
                          >
                            <Plus className="w-3.5 h-3.5 text-white" />
                          </button>
                        </div>
                      </div>
                    )}
                  </div>
                );
              })}
            </div>

            {/* Bottom action */}
            <div className="px-4 pb-6 pt-3 border-t border-[#F3F4F6]">
              <div className="flex items-center justify-between mb-3">
                <p className="text-xs text-[#6B7280]">{totalItems} items logged</p>
                <p className="text-sm font-bold text-[#F97316]">{totalBringing} items bringing</p>
              </div>
              <button
                onClick={() => setShowSummary(true)}
                disabled={totalBringing === 0}
                className="w-full py-3 rounded-2xl bg-[#1A1A2E] text-white text-sm font-bold disabled:opacity-40"
              >
                View Full Summary →
              </button>
            </div>
          </>
        ) : (
          /* Summary view — Mover Quote Format */
          <>
            <div className="flex-1 overflow-y-auto px-4 py-3">
              <div className="flex items-center justify-between mb-3">
                <button onClick={() => setShowSummary(false)} className="text-xs text-[#F97316] font-semibold">← Edit List</button>
                <span className="text-[10px] font-bold text-[#6B7280] uppercase tracking-wider">Mover Quote Sheet</span>
              </div>

              {/* Quote Header Block */}
              <div className="bg-[#1A1A2E] rounded-2xl px-4 py-3 mb-4">
                <p className="text-white text-sm font-bold">📦 Moving Inventory</p>
                <p className="text-[#9CA3AF] text-[11px] mt-0.5">Prepared by: {user?.full_name || "Homeowner"}</p>
                <p className="text-[#9CA3AF] text-[11px]">From: {user?.current_address || "Current Address"}</p>
                <p className="text-[#9CA3AF] text-[11px]">To: {user?.new_address || "New Address"}</p>
                <div className="flex items-center gap-3 mt-2 pt-2 border-t border-white/10">
                  <div className="text-center">
                    <p className="text-white text-base font-bold">{totalBringing}</p>
                    <p className="text-[#9CA3AF] text-[9px] uppercase">Items</p>
                  </div>
                  <div className="w-px h-6 bg-white/10" />
                  <div className="text-center">
                    <p className="text-white text-base font-bold">{roomsWithItems.length}</p>
                    <p className="text-[#9CA3AF] text-[9px] uppercase">Rooms</p>
                  </div>
                  <div className="w-px h-6 bg-white/10" />
                  <div className="text-center">
                    <p className="text-white text-base font-bold">{Object.values(rooms).flat().filter(i => !i.bringing).length}</p>
                    <p className="text-[#9CA3AF] text-[9px] uppercase">Leaving</p>
                  </div>
                </div>
              </div>

              {/* Room-by-room breakdown */}
              {roomsWithItems.map(room => {
                const bringing = rooms[room.id].filter(i => i.bringing);
                if (!bringing.length) return null;
                return (
                  <div key={room.id} className="mb-3">
                    <div className="flex items-center gap-2 mb-1.5">
                      <span className="text-sm">{room.emoji}</span>
                      <p className="text-xs font-bold text-[#1A1A2E] uppercase tracking-wide">{room.label}</p>
                      <span className="text-[10px] text-[#F97316] font-bold bg-[#FFF7ED] px-1.5 py-0.5 rounded-full">{bringing.length} items</span>
                    </div>
                    <div className="bg-[#FAFAFA] rounded-xl border border-[#F3F4F6] overflow-hidden">
                      {bringing.map((item, idx) => (
                        <div key={idx} className={`flex items-center gap-2 px-3 py-2 ${idx < bringing.length - 1 ? "border-b border-[#F3F4F6]" : ""}`}>
                          <div className="w-1.5 h-1.5 rounded-full bg-[#F97316] flex-shrink-0" />
                          <span className="text-xs text-[#1A1A2E] font-medium">{item.name}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                );
              })}

              {/* Leaving behind — compact */}
              {Object.values(rooms).flat().some(i => !i.bringing) && (
                <div className="mt-3 pt-3 border-t border-[#F3F4F6]">
                  <p className="text-[10px] font-bold text-[#9CA3AF] uppercase tracking-wider mb-2">🚫 Not Moving (Leave Behind)</p>
                  <div className="bg-[#FEF2F2] rounded-xl border border-[#FEE2E2] px-3 py-2">
                    {ROOMS.flatMap(room =>
                      rooms[room.id].filter(i => !i.bringing).map((item, idx) => (
                        <div key={`${room.id}-${idx}`} className="flex items-center gap-2 py-1">
                          <X className="w-2.5 h-2.5 text-[#EF4444] flex-shrink-0" />
                          <span className="text-xs text-[#EF4444] line-through">{item.name}</span>
                          <span className="text-[10px] text-[#9CA3AF] ml-auto">{ROOMS.find(r => r.id === room.id)?.label}</span>
                        </div>
                      ))
                    )}
                  </div>
                </div>
              )}

              <p className="text-[10px] text-[#9CA3AF] text-center mt-4">Generated by EZ Move AI · {new Date().toLocaleDateString()}</p>
            </div>

            {/* Email CTA */}
            <div className="px-4 pb-6 pt-3 border-t border-[#F3F4F6]">
              <p className="text-[11px] text-[#6B7280] text-center mb-3">Email this to movers for accurate quotes</p>
              {sent ? (
                <div className="flex items-center justify-center gap-2 py-3 bg-[#F0FDF4] rounded-2xl">
                  <CheckCircle2 className="w-4 h-4 text-[#059669]" />
                  <span className="text-sm font-bold text-[#059669]">Sent to {user?.email}</span>
                </div>
              ) : (
                <button
                  onClick={handleEmail}
                  disabled={sending}
                  className="w-full py-3 rounded-2xl bg-[#F97316] text-white text-sm font-bold flex items-center justify-center gap-2"
                >
                  {sending ? <Loader2 className="w-4 h-4 animate-spin" /> : <Mail className="w-4 h-4" />}
                  {sending ? "Sending…" : "Email Quote Sheet to Movers"}
                </button>
              )}
            </div>
          </>
        )}
      </div>
    </div>
  );
}