import { useState, useEffect } from "react";
import { base44 } from "@/api/base44Client";
import { ChevronRight, Mail, Loader2, CheckCircle2, Trash2, Plus } from "lucide-react";

const LISTS = [
  { key: "move",   label: "Move List",   emoji: "📦", color: "bg-blue-500",   light: "bg-blue-50 border-blue-200",   text: "text-blue-700",   desc: "Things you're taking with you" },
  { key: "junk",   label: "Junk It",     emoji: "🗑️", color: "bg-red-500",    light: "bg-red-50 border-red-200",     text: "text-red-700",    desc: "Trash / haul away" },
  { key: "donate", label: "Donate",      emoji: "🫶", color: "bg-emerald-500", light: "bg-emerald-50 border-emerald-200", text: "text-emerald-700", desc: "Give away or sell" },
];

const QUICK_ITEMS = [
  "Sofa", "Bed Frame", "Mattress", "Dresser", "Dining Table", "Chairs",
  "TV", "TV Stand", "Bookcase", "Desk", "Office Chair", "Refrigerator",
  "Microwave", "Washer", "Dryer", "Couch", "Coffee Table", "Nightstand",
  "Wardrobe", "Rug", "Lamps", "Patio Furniture", "Grill", "Bikes",
  "Storage Bins", "Boxes", "Tools", "Lawn Mower", "Artwork", "Mirrors",
];

export default function MyStuffTab({ user }) {
  const [activeList, setActiveList] = useState(null); // null = home dashboard
  const [lists, setLists] = useState({ move: [], junk: [], donate: [] });
  const [customInput, setCustomInput] = useState("");
  const [sending, setSending] = useState(false);
  const [sent, setSent] = useState(false);

  const currentList = LISTS.find(l => l.key === activeList);
  const items = activeList ? lists[activeList] : [];

  const addItem = (name) => {
    const trimmed = name.trim();
    if (!trimmed) return;
    if (lists[activeList].includes(trimmed)) return;
    setLists(prev => ({ ...prev, [activeList]: [...prev[activeList], trimmed] }));
    setCustomInput("");
  };

  const removeItem = (name) => {
    setLists(prev => ({ ...prev, [activeList]: prev[activeList].filter(i => i !== name) }));
  };

  const handleEmail = async () => {
    setSending(true);
    const listLabel = currentList?.label;
    const body = `${listLabel.toUpperCase()}\n${"=".repeat(40)}\n\n${items.map((item, i) => `${i + 1}. ${item}`).join("\n")}\n\n${"=".repeat(40)}\nTotal: ${items.length} items\n\nGenerated by EZ Move AI`;
    await base44.integrations.Core.SendEmail({ to: user?.email, subject: `My ${listLabel} — EZ Move AI`, body });
    setSending(false);
    setSent(true);
    setTimeout(() => setSent(false), 4000);
  };

  const totalItems = Object.values(lists).reduce((sum, arr) => sum + arr.length, 0);

  // ── Dashboard (no active list) ──────────────────────────────────────────────
  if (!activeList) {
    return (
      <div className="space-y-3">
        {/* Banner */}
        <div className="bg-[#0F172A] rounded-2xl px-4 py-4">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-white font-black text-base">My Stuff</p>
              <p className="text-slate-400 text-xs mt-0.5">Build your move, junk & donate lists</p>
            </div>
            <div className="text-right">
              <p className="text-slate-400 text-[10px]">Total Items</p>
              <p className="text-orange-400 text-2xl font-black">{totalItems}</p>
            </div>
          </div>
        </div>

        {/* 3 list cards */}
        <div className="space-y-2.5">
          {LISTS.map(list => (
            <button
              key={list.key}
              onClick={() => setActiveList(list.key)}
              className="w-full bg-white rounded-2xl border border-slate-100 shadow-sm px-4 py-4 flex items-center gap-4 active:scale-[0.98] transition-transform text-left"
            >
              <div className={`w-12 h-12 rounded-2xl ${list.color} flex items-center justify-center flex-shrink-0 shadow-sm`}>
                <span className="text-2xl">{list.emoji}</span>
              </div>
              <div className="flex-1 min-w-0">
                <p className="font-black text-slate-800 text-sm">{list.label}</p>
                <p className="text-[11px] text-slate-400 mt-0.5">{list.desc}</p>
              </div>
              <div className="flex items-center gap-2 flex-shrink-0">
                {lists[list.key].length > 0 && (
                  <span className={`text-xs font-black px-2.5 py-1 rounded-full border ${list.light} ${list.text}`}>
                    {lists[list.key].length}
                  </span>
                )}
                <ChevronRight className="w-4 h-4 text-slate-300" />
              </div>
            </button>
          ))}
        </div>
      </div>
    );
  }

  // ── Individual list ─────────────────────────────────────────────────────────
  return (
    <div className="space-y-3">
      {/* Header banner */}
      <div className="bg-[#0F172A] rounded-2xl px-4 py-3 flex items-center justify-between">
        <button onClick={() => setActiveList(null)} className="text-slate-400 text-xs font-bold flex items-center gap-1">
          ← Back
        </button>
        <div className="text-center">
          <p className="text-white font-black text-sm">{currentList.emoji} {currentList.label}</p>
          <p className="text-slate-400 text-[10px]">{items.length} items</p>
        </div>
        <div className="w-10" />
      </div>

      {/* Quick add items */}
      <div className="bg-white rounded-2xl border border-slate-100 shadow-sm overflow-hidden">
        <div className="px-4 py-2.5 border-b border-slate-50">
          <p className="text-xs font-bold text-slate-700">Quick Add</p>
        </div>
        <div className="px-3 py-2.5 flex flex-wrap gap-1.5">
          {QUICK_ITEMS.filter(i => !items.includes(i)).map(item => (
            <button
              key={item}
              onClick={() => addItem(item)}
              className="text-[10px] px-2.5 py-1 rounded-full font-semibold border bg-slate-50 text-slate-600 border-slate-200 active:bg-slate-200 transition-all"
            >
              + {item}
            </button>
          ))}
        </div>
      </div>

      {/* Custom input */}
      <div className="flex gap-2">
        <input
          value={customInput}
          onChange={e => setCustomInput(e.target.value)}
          onKeyDown={e => e.key === "Enter" && addItem(customInput)}
          placeholder="Type any item..."
          className="flex-1 px-4 py-3 rounded-2xl border border-slate-200 text-sm focus:outline-none focus:border-orange-400 focus:ring-2 focus:ring-orange-400/10 bg-white"
        />
        <button
          onClick={() => addItem(customInput)}
          disabled={!customInput.trim()}
          className="w-12 h-12 rounded-2xl bg-orange-500 text-white flex items-center justify-center disabled:opacity-30 active:scale-95 transition-transform"
        >
          <Plus className="w-5 h-5" />
        </button>
      </div>

      {/* Items list */}
      {items.length > 0 && (
        <div className="bg-white rounded-2xl border border-slate-100 shadow-sm overflow-hidden">
          <div className={`px-4 py-2.5 border-b ${currentList.light} border-opacity-50`}>
            <p className={`text-xs font-bold ${currentList.text}`}>{currentList.emoji} {currentList.label} ({items.length})</p>
          </div>
          <div className="divide-y divide-slate-50 max-h-72 overflow-y-auto">
            {items.map(item => (
              <div key={item} className="flex items-center gap-3 px-4 py-2.5">
                <p className="flex-1 text-sm font-semibold text-slate-700">{item}</p>
                <button onClick={() => removeItem(item)} className="text-slate-300 hover:text-red-400 transition-colors">
                  <Trash2 className="w-4 h-4" />
                </button>
              </div>
            ))}
          </div>

          {/* Email button */}
          <div className="px-4 py-3 border-t border-slate-50">
            {sent ? (
              <div className="flex items-center justify-center gap-2 py-2.5 bg-emerald-50 rounded-xl">
                <CheckCircle2 className="w-4 h-4 text-emerald-500" />
                <span className="text-sm font-bold text-emerald-600">Sent to {user?.email}</span>
              </div>
            ) : (
              <button
                onClick={handleEmail}
                disabled={sending}
                className={`w-full py-3 rounded-xl text-white text-sm font-bold flex items-center justify-center gap-2 ${currentList.color}`}
              >
                {sending ? <Loader2 className="w-4 h-4 animate-spin" /> : <Mail className="w-4 h-4" />}
                {sending ? "Sending…" : "Email This List"}
              </button>
            )}
          </div>
        </div>
      )}

      {items.length === 0 && (
        <div className="bg-white rounded-2xl border border-dashed border-slate-200 py-10 text-center">
          <p className="text-3xl mb-2">{currentList.emoji}</p>
          <p className="text-sm font-bold text-slate-500">No items yet</p>
          <p className="text-xs text-slate-400 mt-1">Tap quick add above or type any item</p>
        </div>
      )}
    </div>
  );
}